interactions:
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "hi"}], "model":
      "claude-2.1"}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '92'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA0yOTYvCQBBEf4t1nhUjGGGu4sfJg7C5yBLGpNHgpGdM9yzrhvz3JWEFTwWvHkX1
        aGpYtHItF9mqyI/d5ft3ly8/i8f2FjdxvT/BQJ+RRotE3JVg0AU/AifSiDpWGLShJg+LyrtU08dy
        nsGgCqzECnvuXyNKP6M+hcWBvA8zDF8GoiGWHTkJDAviutTUMf4LoUcirgiWk/cGaXpiezQck5Ya
        7sQCmy0MQtJ3lA/DHwAAAP//AwAGMD4r5gAAAA==
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c2260768b6d42de-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:41:45 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      anthropic-ratelimit-requests-limit:
      - '2000'
      anthropic-ratelimit-requests-remaining:
      - '1999'
      anthropic-ratelimit-requests-reset:
      - '2024-09-12T19:41:54Z'
      anthropic-ratelimit-tokens-limit:
      - '400000'
      anthropic-ratelimit-tokens-remaining:
      - '400000'
      anthropic-ratelimit-tokens-reset:
      - '2024-09-12T19:41:45Z'
      request-id:
      - req_01QtGTbuSEodAJbf67oDfmmh
      via:
      - 1.1 google
      x-cloud-trace-context:
      - f46be5074690ff1ab6e460282f1869e6
    status:
      code: 200
      message: OK
version: 1
