interactions:
- request:
    body: '{"messages": [{"content": "hi", "role": "user"}], "model": "gpt-3.5-turbo",
      "n": 1, "stream": false, "temperature": 0.7}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '120'
      content-type:
      - application/json
      host:
      - api.openai.com
      user-agent:
      - OpenAI/Python 1.45.0
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.45.0
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1SQQVPCMBSE7/0Vz5yp04KA9uIw6gh61ZPjMCF9lECa10lelcrw352UQvWSw37Z
        zW4OEYDQuchAqI1kVVYmnk22P8+vszdj86f30f4lbb7G8iFf3OweTSMGwUGrLSo+u64VlZVB1mRP
        WDmUjCE1nQ4n6TRJk0kLSsrRBFtRcTy6HsdcuxXFSTocd84NaYVeZPARAQAc2jN0tDnuRQbJ4KyU
        6L0sUGSXSwDCkQmKkN5rz9KyGPRQkWW0be05GkNXMKdvUNLCAk4GaKgGplw293+NDte1l6G4rY3p
        9OOliaGicrTyHb/oa2213ywdSk82vOqZKtHSYwTw2S6u/40QlaOy4iXTDm0IvD2lif6Le3bXMSaW
        ppfTadS1E77xjOVyrW2BrnK6Hd9uOEa/AAAA//8DAL+Mx137AQAA
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c22607a7819333c-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:41:46 GMT
      Server:
      - cloudflare
      Set-Cookie:
      - __cf_bm=f7v_MvlErsImr51Og1usyf7X4zzvka6uCqXxZswcHYI-1726170106-1.0.1.1-EUkkTCRnG9XfFNPrACRJTv42yT1t0Qm_u8BW35BzwvKMMjq2PyEDq8E4OF9p5uNTJZd0O4StHmwNZuFFhVum3Q;
        path=/; expires=Thu, 12-Sep-24 20:11:46 GMT; domain=.api.openai.com; HttpOnly;
        Secure; SameSite=None
      - _cfuvid=I7ks44mbQ8awsQH7lkSMvqmCKVg7OPTwXtjvLx8xLkg-1726170106480-0.0.1.1-604800000;
        path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None
      Transfer-Encoding:
      - chunked
      X-Content-Type-Options:
      - nosniff
      access-control-expose-headers:
      - X-Request-ID
      alt-svc:
      - h3=":443"; ma=86400
      openai-organization:
      - langchain
      openai-processing-ms:
      - '230'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15552000; includeSubDomains; preload
      x-ratelimit-limit-requests:
      - '10000'
      x-ratelimit-limit-tokens:
      - '50000000'
      x-ratelimit-remaining-requests:
      - '9999'
      x-ratelimit-remaining-tokens:
      - '49999982'
      x-ratelimit-reset-requests:
      - 6ms
      x-ratelimit-reset-tokens:
      - 0s
      x-request-id:
      - req_064900ebb75d94dde4102c7c75471288
    status:
      code: 200
      message: OK
version: 1
