interactions:
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "hi"}], "model":
      "claude-2.1", "system": "respond in italian"}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '124'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA0yOUUvDQBCEf4vzfBXTFsR7FRH61pbQiki4JGs5etlNs3tQCfnvkoDg08DMx8yM
        iC08Or1UT8UmvpwO7/vdx7F720n9ncvyXDMc7KenmSLVcCE4DJJmI6hGtcAGh05aSvBoUsgtrdaP
        BRwaYSM2+M/xr8ToPuOLeLzGIA+YvhzUpK8GCioMD+K2sjzM40ugdMvEDcFzTskhL0f8iMh9tsrk
        SqzwxdZBsv23nqfpFwAA//8DANk5AAzlAAAA
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c226080eed042de-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:41:47 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      anthropic-ratelimit-requests-limit:
      - '2000'
      anthropic-ratelimit-requests-remaining:
      - '1999'
      anthropic-ratelimit-requests-reset:
      - '2024-09-12T19:41:54Z'
      anthropic-ratelimit-tokens-limit:
      - '400000'
      anthropic-ratelimit-tokens-remaining:
      - '400000'
      anthropic-ratelimit-tokens-reset:
      - '2024-09-12T19:41:47Z'
      request-id:
      - req_011ee6R6bXRqcFuSxUUjNrrk
      via:
      - 1.1 google
      x-cloud-trace-context:
      - d28033e5f6b5bdeb994f806cfd5ef250
    status:
      code: 200
      message: OK
version: 1
