interactions:
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "what are
      my favorite pets?"}], "model": "claude-3-haiku-20240307", "temperature": 0.0,
      "tools": [{"name": "update_favorite_pets", "description": "Add the list of favorite
      pets.", "input_schema": {"type": "object", "properties": {"pets": {"description":
      "List of favorite pets to set.", "type": "array", "items": {"type": "string"}}},
      "required": ["pets"]}}, {"name": "delete_favorite_pets", "description": "Delete
      the list of favorite pets.", "input_schema": {"type": "object", "properties":
      {}}}, {"name": "list_favorite_pets", "description": "List favorite pets if any.",
      "input_schema": {"type": "object", "properties": {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '692'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1SPzWrDMBCE32XPMvivpOjWtEmg+OBi6KUUIexNbCJLineVYozfvcil0B5ndvbb
        nQWGDiSMdFFpdnivsWre9g/Pp7m7NZX3+7suQQDPHmMKifQFQcDkTDQ00UCsLYOA0XVoQEJrdOgw
        KZJeD9eQ5GlepkW6AwGts4yWQX4sv0R2zqhAEbn9EXVQaXbKvg7107EYsz6v++PwOlcvugEBVo9x
        zwzE6qzvbhoYlUemSLA+MMhlXT8FEDuvJtTk7P8724DwFtC2CNIGYwSErZdcfhiK3RUtgSyLnQAX
        +K9XPK7rNwAAAP//AwD0u4b8NgEAAA==
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c2264211ca67d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:16 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_01YEa7nkfD47qbQHnVPBYhJk
      via:
      - 1.1 google
      x-cloud-trace-context:
      - 7c0114aa8b2a4e8c16c2d8daf636cd57
    status:
      code: 200
      message: OK
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "what are
      my favorite pets?"}, {"role": "assistant", "content": [{"type": "tool_use",
      "name": "list_favorite_pets", "input": {}, "id": "toolu_01G1wEPAF3m1h2PhFiJyLDaS"}]},
      {"role": "user", "content": [{"type": "tool_result", "content": "cats, dogs",
      "tool_use_id": "toolu_01G1wEPAF3m1h2PhFiJyLDaS", "is_error": false}]}], "model":
      "claude-3-haiku-20240307", "temperature": 0.0, "tools": [{"name": "update_favorite_pets",
      "description": "Add the list of favorite pets.", "input_schema": {"type": "object",
      "properties": {"pets": {"description": "List of favorite pets to set.", "type":
      "array", "items": {"type": "string"}}}, "required": ["pets"]}}, {"name": "delete_favorite_pets",
      "description": "Delete the list of favorite pets.", "input_schema": {"type":
      "object", "properties": {}}}, {"name": "list_favorite_pets", "description":
      "List favorite pets if any.", "input_schema": {"type": "object", "properties":
      {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '982'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAAzxPy2rDMBD8FTFnuTiPNkTHtLfSXEppoBQjrI1j4qxc7arUGP97cfo4zTCPXWZE
        G+BwkaYqF7uHx2Fz/9S/+APfPu+3+8a/3h1goUNPc4pEfEOwSLGbBS/SinpWWFxioA4OdedzoGJV
        nHx7zsWyXK7LVbmBRR1ZiRXubfy7qPQ1d6/gsPNCwUQ2eiITs/ZZrRliTuboP2NqlUxPKsYnMrWf
        CQcTYiM3mN4tRGNfJfISGQ7EodKcGL+G0EcmrgmOc9dZ5OsUN6LlPmul8UwscOttafHz+19bbKbp
        GwAA//8DADNBU2UpAQAA
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c2264255a357d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:16 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_01K5fW82CXS8KAseCYxUj1Up
      via:
      - 1.1 google
      x-cloud-trace-context:
      - b30a38cdc34841db989f49402066a77c
    status:
      code: 200
      message: OK
version: 1
