interactions:
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "please forget
      what i told you about my favorite animals"}], "model": "claude-3-haiku-20240307",
      "temperature": 0.0, "tools": [{"name": "update_favorite_pets", "description":
      "Add the list of favorite pets.", "input_schema": {"type": "object", "properties":
      {"pets": {"description": "List of favorite pets to set.", "type": "array", "items":
      {"type": "string"}}}, "required": ["pets"]}}, {"name": "delete_favorite_pets",
      "description": "Delete the list of favorite pets.", "input_schema": {"type":
      "object", "properties": {}}}, {"name": "list_favorite_pets", "description":
      "List favorite pets if any.", "input_schema": {"type": "object", "properties":
      {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '721'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1SPQU/DMAyF/4vPqdSuFaU5M22HHjYNDgihKGq8rixNSu1QRtX/jlKEBMf3/PzZ
        b4bOgISeWpVmx1OxK6equmXnsDt8Pd09mOptCwL4NmBMIZFuEQSM3kZDE3XE2jEI6L1BCxIaq4PB
        JE8uuruGZJNuijRPSxDQeMfoGOTL/Etk760KFJHrH1EHlWaHYgpDWx/b+nH6PD0b3Nfl9gICnO7j
        nkGLjOqsP/zYMaoBmSLDDYFBzsvyKoDYD2pETd79v7QOCN8DugZBumCtgLA2k/MPQ7G/oiOQRZEJ
        8IH/evn9snwDAAD//wMA+TpaPDgBAAA=
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c2264295ea07d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:17 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_01YNnZBauFHN1YpVfSk9uK1b
      via:
      - 1.1 google
      x-cloud-trace-context:
      - 47b1a9fb296aab8115da18fd5d101d9c
    status:
      code: 200
      message: OK
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "please forget
      what i told you about my favorite animals"}, {"role": "assistant", "content":
      [{"type": "tool_use", "name": "delete_favorite_pets", "input": {}, "id": "toolu_01P4wupgLQgLTwxSYdeHL7Eh"}]},
      {"role": "user", "content": [{"type": "tool_result", "content": "null", "tool_use_id":
      "toolu_01P4wupgLQgLTwxSYdeHL7Eh", "is_error": false}]}], "model": "claude-3-haiku-20240307",
      "temperature": 0.0, "tools": [{"name": "update_favorite_pets", "description":
      "Add the list of favorite pets.", "input_schema": {"type": "object", "properties":
      {"pets": {"description": "List of favorite pets to set.", "type": "array", "items":
      {"type": "string"}}}, "required": ["pets"]}}, {"name": "delete_favorite_pets",
      "description": "Delete the list of favorite pets.", "input_schema": {"type":
      "object", "properties": {}}}, {"name": "list_favorite_pets", "description":
      "List favorite pets if any.", "input_schema": {"type": "object", "properties":
      {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '1007'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1SPT0vDQBDFv8ow522JaVDcaykiBQ/qTSRss9Nm6WYm7s6WhpLvLi0Kenrwe3/g
        XTB4tDjkQ1vdPfGmvG75PI1Tc1+v/fpl698GNKjTSNcU5ewOhAaTxCtwOYesjhUNDuIposUuuuJp
        sVr0LhzLoq7qplpVD2iwE1ZiRftx+V1UOl+7N7H4DL07EXiKpORBe4LAe0mD0yAMbidFYZKSYO9O
        koISjKR5Ce89QQxZQfb/Lehdhh0RQxfJJfJLnD8NZpWxTeSyMFok9q2WxPhjZPoqxB2h5RKjwXI7
        bS8YeCzaqhyJM9rmsTYoRf+yejXP3wAAAP//AwAfeAOhUwEAAA==
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c22642d5b287d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:18 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_014cbfoh7Rw7FNsEJP4cxFAJ
      via:
      - 1.1 google
      x-cloud-trace-context:
      - f77bf5cf43dc2a3b43753257332c2708
    status:
      code: 200
      message: OK
version: 1
