interactions:
- request:
    body: '{"messages": [{"content": "what''s the latest news about FooBar", "role":
      "user"}], "model": "gpt-4o", "n": 1, "stream": false, "temperature": 0.0, "tools":
      [{"type": "function", "function": {"name": "get_context", "description": "Get
      context on the question.", "parameters": {"type": "object", "properties": {"question":
      {"description": "The user question", "type": "array", "items": {"type": "string"}}},
      "required": ["question"]}}}, {"type": "function", "function": {"name": "cite_context_sources",
      "description": "Cite which source a claim was based on.", "parameters": {"type":
      "object", "properties": {"claim": {"description": "The claim that was made.",
      "type": "string"}}, "required": ["claim"]}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '706'
      content-type:
      - application/json
      host:
      - api.openai.com
      user-agent:
      - OpenAI/Python 1.45.0
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.45.0
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA2xSy2rjMBTd+yvEXdeD7SRO6l3TFwNT6GSg0DbFKMq141aWXOmaNhPy74MUN3bD
        aGHEPToPH2kXMAbVGjIGYsNJ1I0ML9K3ebu4Womfsn2IF+nFn/vq/vr34+Pl+HIGZ46hV68o6Iv1
        Q+i6kUiVVgdYGOSETjWeJmk8jWbnkQdqvUbpaGVD4ViHSZSMw2gSxqOOuNGVQAsZew4YY2znvy6i
        WuMnZMzL+EmN1vISITseYgyMlm4C3NrKElcEZz0otCJULrVqpRwApLXMBZeyNz6s3WDf98SlzOOP
        6cJc3T79Sjgm88Xo6S55+FvTduB3kN42PlDRKnHsZ4Af59mJGWOgeO25JVLus3/SCZ0x4KZsa1Tk
        osNuCe8tWie4hOx5CZITWmIKPyzjK90Su9F6zs0SXvbwTWof/G//MmjJYNFaLrv6uvn+eB9Sl43R
        K3tSLxSVquwmN8it/81h28GXm/eB9tuFQmN03VBO+g2Vk51ND6LQP7cejM87kDRxOZhHadDFBLu1
        hHVeVKpE05jKvwUomjyZpMmY44hPINgH/wAAAP//AwCRIq0nFAMAAA==
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c22739f0a7443ec-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:54:50 GMT
      Server:
      - cloudflare
      Set-Cookie:
      - __cf_bm=cG4kr1ppK1g8sj5yIhmN1BJ_aJlDy5k88mnQ.mim9pY-1726170890-1.0.1.1-cme6TvzpA0dQ4FUyLDuhSJutk1i71DUkswti2vKI9mjTP_tKFW56045UgJv7FRBi7zLKUCv9Czq_IFW1TBZ48A;
        path=/; expires=Thu, 12-Sep-24 20:24:50 GMT; domain=.api.openai.com; HttpOnly;
        Secure; SameSite=None
      - _cfuvid=7gpwk9UNPB1b1ikhcH9ycmE8s2xESd0JZq2bhDozIkM-1726170890581-0.0.1.1-604800000;
        path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None
      Transfer-Encoding:
      - chunked
      X-Content-Type-Options:
      - nosniff
      access-control-expose-headers:
      - X-Request-ID
      alt-svc:
      - h3=":443"; ma=86400
      openai-organization:
      - langchain
      openai-processing-ms:
      - '281'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15552000; includeSubDomains; preload
      x-ratelimit-limit-requests:
      - '10000'
      x-ratelimit-limit-tokens:
      - '30000000'
      x-ratelimit-remaining-requests:
      - '9999'
      x-ratelimit-remaining-tokens:
      - '29999973'
      x-ratelimit-reset-requests:
      - 6ms
      x-ratelimit-reset-tokens:
      - 0s
      x-request-id:
      - req_847cdd27b2bd487528247dca34f11e88
    status:
      code: 200
      message: OK
- request:
    body: '{"messages": [{"content": "what''s the latest news about FooBar", "role":
      "user"}, {"content": null, "role": "assistant", "tool_calls": [{"type": "function",
      "id": "call_1w7RrDGZL2ae2BR3ZM2Vzmty", "function": {"name": "get_context", "arguments":
      "{\"question\": [\"latest news about FooBar\"]}"}}]}, {"content": "FooBar company
      just raised 1 Billion dollars!\n\nFooBar company is now only hiring AI''s\n\nFooBar
      company was founded in 2019\n\nFooBar company makes friendly robots", "role":
      "tool", "tool_call_id": "call_1w7RrDGZL2ae2BR3ZM2Vzmty"}], "model": "gpt-4o",
      "n": 1, "stream": false, "temperature": 0.0, "tools": [{"type": "function",
      "function": {"name": "get_context", "description": "Get context on the question.",
      "parameters": {"type": "object", "properties": {"question": {"description":
      "The user question", "type": "array", "items": {"type": "string"}}}, "required":
      ["question"]}}}, {"type": "function", "function": {"name": "cite_context_sources",
      "description": "Cite which source a claim was based on.", "parameters": {"type":
      "object", "properties": {"claim": {"description": "The claim that was made.",
      "type": "string"}}, "required": ["claim"]}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      connection:
      - keep-alive
      content-length:
      - '1170'
      content-type:
      - application/json
      cookie:
      - __cf_bm=cG4kr1ppK1g8sj5yIhmN1BJ_aJlDy5k88mnQ.mim9pY-1726170890-1.0.1.1-cme6TvzpA0dQ4FUyLDuhSJutk1i71DUkswti2vKI9mjTP_tKFW56045UgJv7FRBi7zLKUCv9Czq_IFW1TBZ48A;
        _cfuvid=7gpwk9UNPB1b1ikhcH9ycmE8s2xESd0JZq2bhDozIkM-1726170890581-0.0.1.1-604800000
      host:
      - api.openai.com
      user-agent:
      - OpenAI/Python 1.45.0
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 1.45.0
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.openai.com/v1/chat/completions
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAAwAAAP//ZFLLbtswELzrK7a89BIbluJHokthtyjcQw8FUrRAHRi0tJJoU1yWu0Ji
        BP73gLJqJ+iFAGc4g9lZviQAypQqB1U0WorW29Fyflh1X+7Wxe+Hz5lZ/gjr7/55nj38/Vnt9uom
        Kmi3x0L+qcYFtd6iGHJnugioBaNrusjm6WJydz/piZZKtFFWexlNaZRNsuloMhult4OwIVMgqxz+
        JAAAL/0ZI7oSn1UOvU2PtMisa1T55RGACmQjojSzYdFO1M2VLMgJuj71GgOCDghMLQJVIA2C1YIs
        4PCJQe+oE/hKtNIh37iNS8fDDeKw2h1h37FA0IaxhBRWxlpDDkqyVgf+sHHZfwrD4OgJyNkjNCYY
        V8Py20ceR/9f1NkSjtSBNQeElgJCiaKNZSAHUX6OyQidL2PUT2+HC1h1rGO3rrN2wE+XtizVPtCO
        B/6CV8YZbrYBNZOLzbCQVz17SgAe+61074pWPlDrZSt0QBcN09mwFXX9B1d2uhhIIdH2jep+kQwJ
        FR9ZsN1WxtUYfDDnJVV+m83m2VTjrZ6p5JS8AgAA//8DAE2xyH6tAgAA
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c2273a2be4143ec-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:54:51 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Content-Type-Options:
      - nosniff
      access-control-expose-headers:
      - X-Request-ID
      alt-svc:
      - h3=":443"; ma=86400
      openai-organization:
      - langchain
      openai-processing-ms:
      - '928'
      openai-version:
      - '2020-10-01'
      strict-transport-security:
      - max-age=15552000; includeSubDomains; preload
      x-ratelimit-limit-requests:
      - '10000'
      x-ratelimit-limit-tokens:
      - '30000000'
      x-ratelimit-remaining-requests:
      - '9999'
      x-ratelimit-remaining-tokens:
      - '29999932'
      x-ratelimit-reset-requests:
      - 6ms
      x-ratelimit-reset-tokens:
      - 0s
      x-request-id:
      - req_9aca0910ecb4b7b2d4e8cbe6b16c44ba
    status:
      code: 200
      message: OK
version: 1
