interactions:
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "my favorite
      pets are cats and dogs"}], "model": "claude-3-haiku-20240307", "temperature":
      0.0, "tools": [{"name": "update_favorite_pets", "description": "Add the list
      of favorite pets.", "input_schema": {"type": "object", "properties": {"pets":
      {"description": "List of favorite pets to set.", "type": "array", "items": {"type":
      "string"}}}, "required": ["pets"]}}, {"name": "delete_favorite_pets", "description":
      "Delete the list of favorite pets.", "input_schema": {"type": "object", "properties":
      {}}}, {"name": "list_favorite_pets", "description": "List favorite pets if any.",
      "input_schema": {"type": "object", "properties": {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '700'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA1SQTU/CQBCG/0ozFy9L0kIV3KtBEy5yED9CzGZpRyhsd2tnhohN/7vZEqKeJvPO
        vM98dFCVoKGmrUmzp002W5abOQm2D6tjPl9+311PQQGfGoxdSGS3CAra4KJgiSpi6xkU1KFEBxoK
        Z6XE0WS0s9VBRuN0nKeTNFKK4Bk9g153FyLjV/QOQcPjwZ5U4pCvKJGmtIzJKUibfNhjaCvGpEEm
        Db369YfgjFBcabgj5mLSbGF3q/rtdZzTanH/ciP79jbbP4MCb+voO9PNBWwiODJ8Iwy6gyHXayjs
        oJdhS/De9+8KiENjWrQU/P/5Q4HwU9AXCNqLcwpk+JfuzmTD4YCeQOeTmYIg/Febpn3/AwAA//8D
        AAnl5U6OAQAA
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c226418d9607d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:14 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_012DXZcYQjyN7MhU5FDxjtcE
      via:
      - 1.1 google
      x-cloud-trace-context:
      - df7daff27fed534057329e4a2073231e
    status:
      code: 200
      message: OK
- request:
    body: '{"max_tokens": 1024, "messages": [{"role": "user", "content": "my favorite
      pets are cats and dogs"}, {"role": "assistant", "content": [{"text": "Okay,
      let''s update your favorite pets:", "type": "text"}, {"type": "tool_use", "name":
      "update_favorite_pets", "input": {"pets": ["cats", "dogs"]}, "id": "toolu_01JahUmYX24sUJFW6ujr91jV"}]},
      {"role": "user", "content": [{"type": "tool_result", "content": "null", "tool_use_id":
      "toolu_01JahUmYX24sUJFW6ujr91jV", "is_error": false}]}], "model": "claude-3-haiku-20240307",
      "temperature": 0.0, "tools": [{"name": "update_favorite_pets", "description":
      "Add the list of favorite pets.", "input_schema": {"type": "object", "properties":
      {"pets": {"description": "List of favorite pets to set.", "type": "array", "items":
      {"type": "string"}}}, "required": ["pets"]}}, {"name": "delete_favorite_pets",
      "description": "Delete the list of favorite pets.", "input_schema": {"type":
      "object", "properties": {}}}, {"name": "list_favorite_pets", "description":
      "List favorite pets if any.", "input_schema": {"type": "object", "properties":
      {}}}]}'
    headers:
      accept:
      - application/json
      accept-encoding:
      - gzip, deflate
      anthropic-version:
      - '2023-06-01'
      connection:
      - keep-alive
      content-length:
      - '1078'
      content-type:
      - application/json
      host:
      - api.anthropic.com
      user-agent:
      - Anthropic/Python 0.34.2
      x-stainless-arch:
      - arm64
      x-stainless-async:
      - 'false'
      x-stainless-lang:
      - python
      x-stainless-os:
      - MacOS
      x-stainless-package-version:
      - 0.34.2
      x-stainless-runtime:
      - CPython
      x-stainless-runtime-version:
      - 3.11.9
    method: POST
    uri: https://api.anthropic.com/v1/messages
  response:
    body:
      string: !!binary |
        H4sIAAAAAAAAA0yP3UrDQBCFX2U51xtJWquwd6XojQgKghSRsGbHNjSZjZnZEhPy7pKi4NWB7/zA
        mVAHOLRyKPPiZtBtfz8+PvOu3T6M+3F4eXq9g4V+d7SkSMQfCBZ9bBbgRWpRzwqLNgZq4FA1PgXK
        1tnR16eUrfLVdb7Ob2FRRVZihXub/haVhqV7EYd9TL359OfY10qmIxVz9GcyH0RsUhe8UjAaTeVV
        jOdgQjzIFeZ3C9HYlT15iQwH4lBq6hm/htBXIq4IjlPTWKTLDTeh5i5pqfFELHCbVWERk/5nxWae
        fwAAAP//AwAkmYIBJQEAAA==
    headers:
      CF-Cache-Status:
      - DYNAMIC
      CF-RAY:
      - 8c22641dd85c7d18-EWR
      Connection:
      - keep-alive
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json
      Date:
      - Thu, 12 Sep 2024 19:44:15 GMT
      Server:
      - cloudflare
      Transfer-Encoding:
      - chunked
      X-Robots-Tag:
      - none
      request-id:
      - req_014qAYuxj8ijupvxJoXBsEbS
      via:
      - 1.1 google
      x-cloud-trace-context:
      - 6ed1d238840ac4d83f3c4b71c918af78
    status:
      code: 200
      message: OK
version: 1
